### ISSUE TITLE
The disk image's directory is corrupt (and possibly the disk image itself is too)

### ISSUE THREAD

**Issue by andlabs** [misterblack1/c64-testpatterns#1]
The "TEST PATTERN" file appears to have a size of 0 blocks, and loading it in VICE yields "?FILE NOT FOUND ERROR". Doing `hexdump -C` shows the file is present from byte offset 0x00015000 to 0x000165C0 (or is that two separate files?), and the file has the "not properly closed after writing" bit (`*` in directory listing) set.

**Comment by misterblack1** [comment]
You're right! It's not working in VICE -- let me double check on my SD2IEC.

**Comment by misterblack1** [comment]
Yeah don't quite get it -- this image works perfectly on a SDIEC. Just tested it on a stock C64 with stock Kernel and it loaded perfectly. (It does show a PRG size of 0.) And even more strange is I created it on VICE (As you can tell from the name.) 

I'll make a new one.

**Comment by misterblack1** [comment]
Ok new one is up -- try now.

**Comment by andlabs** [comment]
Yep that does work; thanks!

But now I wonder why the old image works with an SD2IEC... I only have high-density 5.25" floppies on me right now, otherwise I'd try it with a real disc and report back what happens. (And I did try to compare with a hex dump; one of the bytes after the filename is different, but since the file now lives on a different sector I didn't try to just edit the bytes in the old file and try again, since I don't know that much about Commodore DOS to figure out what the right values should be.)

**Comment by misterblack1** [comment]
Who knows but it definitely looked corrupted -- the one I uploaded here was the one I had on my SDIEC used for all my testing. Odd! Thanks for letting me know.
